DROP TABLE IF EXISTS AGENTES;

CREATE TABLE AGENTES(
	EMAIL VARCHAR PRIMARY KEY NOT NULL UNIQUE,
	PASSWORD VARCHAR(60) NOT NULL
);

INSERT INTO AGENTES (EMAIL, PASSWORD)
VALUES
('who@fbi.com', 'me'),
('where@fbi.com', 'there'),
('how@fbi.com', 'exactly');

SELECT * FROM AGENTES;
